class TestFail(Exception):
    """
    Exception raised when test has failed.
    """
